name: user_registration
description: A new Flutter project.

publish_to: 'none' 

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  equatable: ^2.0.3
  cupertino_icons: ^1.0.2 
  injectable:  
  get_it: 
  firebase_core: ^2.8.0
  firebase_auth:
  either_dart: ^1.0.0
  provider: ^6.1.1
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator:   
  build_runner:  

flutter:
  uses-material-design: true
